# Generated by Django 2.0.2 on 2018-10-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='plz enter ur name ', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.TextField(help_text='plz be short ', max_length=500)),
            ],
        ),
    ]
