# Generated by Django 2.0.2 on 2018-10-03 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='productimage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.ProductImage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productimage',
            name='title',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
