# Generated by Django 2.0.2 on 2018-10-03 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20181003_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productimage',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='title',
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
            preserve_default=False,
        ),
    ]
