# Generated by Django 2.0.2 on 2018-10-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20181003_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfeautre',
            name='hits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='descrip your Product', max_length=1500),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='قیمت ها به تومان می باشد.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(help_text='Enter uniqe title', max_length=120),
        ),
    ]
