# Generated by Django 2.0.2 on 2018-10-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20181006_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hits',
            field=models.IntegerField(default=0),
        ),
    ]
